Jest testing for use cases and Refactoring
Dhairya-Khara/TLI-Voiceflow-Project pull request #76
Opened 2022-11-21 06:19 UTC by aidanmrli

Implemented Jest testing for all use cases. The test files can be found in the server/src/__test__ folders. To run the tests, go to the server directory and run npm test.

Additionally, revamped and refactored existing use cases: added catch errors, extracted methods in various files to improve code smells and reduce large chunks of code.

To continue, we would like to develop a test suite for the controllers and for the front-end on the client-side eventually. The use-cases will always be a priority, and we can also think about making better use of Jest Mocking for easier and better designed tests.

2022-11-21 21:05 UTC, Dhairya-Khara requested changes
Great work guys. The only feedback I have is that in many files, there is commented code. We should remove those to avoid adding to code smells.

2022-11-21 21:05 UTC, Dhairya-Khara commented on server/src/UseCases/TranscriptUseCases/transcriptUploadInteractor.js
> +            //transcriptNames.push(subInfo.keys()[0])})
We can remove these comments (they are unnecessary and adding to code smells)

2022-11-21 21:05 UTC, Dhairya-Khara commented on server/src/__tests__/UseCases/GetUseCases/getOneTranscriptIntentsInteractor.test.js
> +    // it correctly returns a user's transcript's intents
These comments can also be removed.

2022-11-21 21:05 UTC, Dhairya-Khara commented on server/src/__tests__/UseCases/TranscriptUseCases/transcriptUploadInteractor.test.js
> +        // await expect(uploadTranscriptInteractor(user, sampleTranscriptJSON, sampleTranscriptFilename)).rejects;
comment!

2022-11-22 00:31 UTC, aidanmrli commented
> Great work guys. The only feedback I have is that in many files, there is commented code. We should remove those to avoid adding to code smells.

Thank you for the feedback, this is a good point that I missed out. Thank you for catching this. The changes have been made.

2022-11-22 20:18 UTC, merged